### ISSUE TITLE
Debug and Server is disabled, and how to make code completion work?

### ISSUE THREAD

**Issue by geekfrog** [DST-Tools/DSTEd#2]
![default](https://cloud.githubusercontent.com/assets/14846727/26600484/e02e5802-45ae-11e7-91a1-2709d74571ed.png)

where I have gone wrong ?

**Comment by geekfrog** [comment]
OS : win8.1 x64

**Comment by Bizarrus** [comment]
These Menu-entries are placeholder and currently not implemented :)
For the Code-completion is currently only the basic-setup available (Press CMD-SPACE), the full Api will be implemented later (see https://github.com/DST-Tools/DSTEd/blob/master/Source/Resources/DST-API.json)

**Comment by geekfrog** [comment]
I got it
 thanks for you open-source
