### ISSUE TITLE
Windows Build Instructions

### ISSUE THREAD

**Issue by Aida-Enna** [DST-Tools/DSTEd#3]
I wanted to come in and look over the English strings for this project as you requested on the thread, but I needed to set up my environment first, so I thought I'd write down what I had to do as the Windows build instructions. I can't edit the Wiki directly, so I thought I should post it here. Apologies if there's a better way!

1. Download and extract [the source code](https://github.com/DST-Tools/DSTEd/archive/master.zip)
2. Make sure [Node.js is installed](https://nodejs.org/en/)
3. Restart (Node.js will **not work** until you restart)
4. Install the Electron Packager in the CLI mode (Open command prompt and type "npm install electron-packager -g" without the quotes, hitting enter afterwards)
5. Once that's done, double click the "Build.bat" file.

Once it's complete, the build will be available in the "Build" folder, inside the subfolder that's created there.

**Comment by Bizarrus** [comment]
Build instructions will be added later on the Wiki, Tanks :)

If you start the **Build** Script, the software will builded for the current machine. If you want to Build it for all or for a specific OS, you musst add the Parameter `--all` or `--arch=<OS>` on the `electron-packager` command; i think, its a right way to create specific Build-Files with custom configs for that.

**Comment by Bizarrus** [comment]
Info: if you want to edit the Wiki, fork the repository, edit the Wiki and make a request.
